var Names = {
  list: [
    "Merek",
    "Carac",
    "Ulric",
    "Tybalt",
    "Borin",
    "Sadon",
    "Terrowin",
    "Rowan",
    "Forthwind",
    "Althalos",
    "Fendrel",
    "Brom",
    "Hadrian",
    "Lord Crewe",
    "Walter De Bolbec",
    "Earl of Derwintwater",
    "Lord Montagu",
    "Sir John Fenwick of Wallington",
    "Oliver Cromwell",
    "Justice McKinnon",
    "Sir Clifton Writingham",
    "Walter deGrey",
    "Roger de Mowbray",
    "Joseph Rowntree",
    "Geoffrey Chaucer",
    "William of Wykeham",
    "Francis Drake",
    "Simon de Montfort",
    "John of Gaunt",
    "William of Orange",
    "Lord Cornwallis",
    "Edmund Cartwright",
    "Charles the Bald",
    "Benedict",
    "Gregory",
    "Peter",
    "Henry",
    "Frederick",
    "Walter",
    "Thomas",
    "Arthur",
    "Bryce",
    "Donald",
    "Leofrick",
    "Letholdus",
    "Lief",
    "Barda",
    "Rulf",
    "Robin",
    "Gavin",
    "Terrin",
    "Terryn",
    "Ronald",
    "Jarin",
    "Cassius",
    "Leo",
    "Cedric",
    "Gavin",
    "Peyton",
    "Josef",
    "Janshai",
    "Doran",
    "Asher",
    "Quinn",
    "Zane",
    "Xalvador",
    "Favian",
    "Destrian",
    "Dain",
    "Lord Falk",
    "Berinon",
    "Millicent",
    "Alys",
    "Ayleth",
    "Anastas",
    "Alianor",
    "Cedany",
    "Ellyn",
    "Helewys",
    "Malkyn",
    "Peronell",
    "Sybbyl",
    "Ysmay",
    "Thea",
    "Jacquelyn",
    "Amelia the Countess of Derwentwater",
    "Gloriana",
    "Good Queen Bess",
    "Catherine of Aragon",
    "Anne of Cleves",
    "Mary, Queen of Scots",
    "Mary of Guise",
    "Arabella",
    "Elizabeth",
    "Hildegard",
    "Brunhild",
    "Adelaide",
    "Alice",
    "Beatrix",
    "Cristiana",
    "Eleanor",
    "Emeline",
    "Isabel",
    "Juliana",
    "Margaret",
    "Matilda",
    "Mirabelle",
    "Rose",
    "Helena",
    "Guinevere",
    "Isolde",
    "Maerwynn",
    "Muriel",
    "Winifred",
    "Godiva",
    "Catrain",
    "Angmar",
    "Gussalen",
    "Jasmine",
    "Josselyn",
    "Maria",
    "Victoria",
    "Gwendolynn",
    "Enndolynn",
    "Janet",
    "Luanda",
    "Krea",
    "Rainydayas",
    "Atheena",
    "Dimia",
    "Phrowenia",
    "Aleida",
    "Ariana",
    "Alexia",
    "Katelyn",
    "Katrina",
    "Loreena",
    "Kaylein",
    "Seraphina",
    "Duraina",
    "Ryia",
    "Farfelee"

  ],

	get: function() {
    var m = new MersenneTwister();
    return this.list[Math.floor((m.random() * this.list.length))];
  }
}