var skillsList = [
  {"name":"Acrobacia",      "damage": "0",     "base": "agi",  "initiative": "0", "limitedTo":"defense"},
  {"name":"Adaga",          "damage": "1d3",   "base": "dex",  "initiative": "-2"},
  {"name":"Arco curto",     "damage": "1d6",   "base": "dex",  "initiative": "-10", "limitedTo":"attack"},
  {"name":"Arco longo",     "damage": "1d6+2", "base": "dex",  "initiative": "-9", "limitedTo":"attack"},
  {"name":"Artes marciais", "damage": "1d3",   "base": "agi",  "initiative": "0"},
  {"name":"Besta",          "damage": "1d6",   "base": "dex",  "initiative": "-15", "limitedTo":"attack"},
  {"name":"Boleadeira",     "damage": "1d6+1", "base": "dex",  "initiative": "-6"},
  {"name":"Boxe",           "damage": "1d3",   "base": "agi",  "initiative": "0"},
  {"name":"Briga",          "damage": "1d3",   "base": "agi",  "initiative": "0"},
  {"name":"Carga",          "damage": "1d4",   "base": "con",  "initiative": "0", "baseClass": "warrior", "limitedTo":"attack"},
  {"name":"Chicote",        "damage": "1d4",   "base": "dex",  "initiative": "-6"},
  {"name":"Dança",          "damage": "1d4",   "base": "agi",  "initiative": "0"},
  {"name":"Espada curta",   "damage": "1d6",   "base": "dex",  "initiative": "-4"},
  {"name":"Espada longa",   "damage": "1d10",  "base": "dex",  "initiative": "-5"},
  {"name":"Esquiva",        "damage": "0",     "base": "agi",  "initiative": "0", "limitedTo":"defense"},
  {"name":"Faca",           "damage": "1d3",   "base": "dex",  "initiative": "-3"},
  {"name":"Finta",          "damage": "0",     "base": "intelligence", "initiative": "0", "limitedTo":"defense"},
  {"name":"Lança",          "damage": "1d6",   "base": "dex",  "initiative": "-6"},
  {"name":"Maça",           "damage": "1d10",  "base": "dex",  "initiative": "-5"},
  {"name":"Machado",        "damage": "1d6+2", "base": "dex",  "initiative": "-7"},
  {"name":"Martelo",        "damage": "1d6",   "base": "dex",  "initiative": "-4"},
  {"name":"Punhal",         "damage": "1d3+1", "base": "dex",  "initiative": "-3"},
  {"name":"Rede",           "damage": "0",     "base": "dex",  "initiative": "-4", "limitedTo":"attack"},
  {"name":"Sabre",          "damage": "1d6+2", "base": "dex",  "initiative": "-6"},
  {"name":"Zarabatana",     "damage": "1d2",   "base": "dex",  "initiative": "-2", "limitedTo":"attack"},
  {"name":"Magia nível 1",  "damage": "1d6",   "base": "will",  "initiative": "-1", "baseClass": "sorcerer"},
  {"name":"Magia nível 2",  "damage": "2d6",   "base": "will",  "initiative": "-2", "baseClass": "sorcerer"},
  {"name":"Magia nível 3",  "damage": "3d6",   "base": "will",  "initiative": "-3", "baseClass": "sorcerer"},
  {"name":"Magia nível 4",  "damage": "4d6",   "base": "will",  "initiative": "-4", "baseClass": "sorcerer"},
  {"name":"Magia nível 5",  "damage": "5d6",   "base": "will",  "initiative": "-5", "baseClass": "sorcerer"},
  {"name":"Magia nível 6",  "damage": "6d6",   "base": "will",  "initiative": "-6", "baseClass": "sorcerer"},
  {"name":"Magia nível 7",  "damage": "7d6",   "base": "will",  "initiative": "-7", "baseClass": "sorcerer"},
  {"name":"Bastão",         "damage": "1d3",   "base": "dex",   "initiative": "-1"},
  {"name":"Garras",         "damage": "1d3",   "base": "dex",   "initiative": "0"},
  {"name":"Foice",          "damage": "1d10+2","base": "dex",   "initiative": "-3"}

];
